DROP TABLE IF EXISTS CRYPTOPUNKS;
CREATE TABLE CRYPTOPUNKS(
    ID INT PRIMARY KEY,
    GENDER VARCHAR(8) NOT NULL,
    ACCESSORIES INT
);

DROP TABLE IF EXISTS ACCESSORY_MASTER;
CREATE TABLE CRYPTOPUNKS_ACCESSORY(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PUNK_ID INT NOT NULL,
    ACCESSORY_ID INT NOT NULL
);

DROP TABLE IF EXISTS ACCESSORY_MASTER;
CREATE TABLE ACCESSORY_MASTER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STRING VARCHAR(60) NOT NULL
);